// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAVVQXb-0EYYadR1jWNBAiicfynrspgxPE',
    appId: '1:93470584453:web:92e688374c6106ad9e43ec',
    messagingSenderId: '93470584453',
    projectId: 'task-manager-19499',
    authDomain: 'task-manager-19499.firebaseapp.com',
    storageBucket: 'task-manager-19499.firebasestorage.app',
    measurementId: 'G-PXV7H487VP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCralLvc38Xe4YqnmO8rJoo017aQkHLf8g',
    appId: '1:93470584453:android:86105637e3201b9d9e43ec',
    messagingSenderId: '93470584453',
    projectId: 'task-manager-19499',
    storageBucket: 'task-manager-19499.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBWxXImLxDvTzCxIOg-ch87iRlEQ1PZJaU',
    appId: '1:93470584453:ios:be5f0d862f4a6cb29e43ec',
    messagingSenderId: '93470584453',
    projectId: 'task-manager-19499',
    storageBucket: 'task-manager-19499.firebasestorage.app',
    androidClientId: '93470584453-9olalrc278gkm3n7gepegurcqut9vgee.apps.googleusercontent.com',
    iosClientId: '93470584453-2j2hs6jsfe0e24oo8f364t1m6p61gio9.apps.googleusercontent.com',
    iosBundleId: 'com.example.taskmanager',
  );

}